name: Test Suite

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pytest.ini'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/test.yml'
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Verify uv installation
      run: uv --version

    - name: Install dependencies
      run: |
        uv pip install --system pytest pytest-asyncio pytest-cov pytest-mock
        uv pip install --system -r requirements.txt

    - name: Run test suite
      run: |
        chmod +x run_tests.sh
        ./run_tests.sh all

    - name: Upload coverage reports (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          .coverage
          htmlcov/
        retention-days: 7
