"""Prompts for TeleCorp LangGraph AI Agent."""

from .persona import TELECORP_PERSONA, TECHNICAL_SUPPORT_PERSONA, BILLING_SUPPORT_PERSONA, SALES_SUPPORT_PERSONA

__all__ = [
    'TELECORP_PERSONA',
    'TECHNICAL_SUPPORT_PERSONA',
    'BILLING_SUPPORT_PERSONA',
    'SALES_SUPPORT_PERSONA'
]